<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $fillable = [
        'name', 'details', 'pessimistic','normal', 'optimistic'
    ];

    public function requirement(){
        return $this->belongsToMany('App\Requirement');
    }
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::saving(function($item){
            $item->estimated=(4*doubleval($item->normal)+doubleval($item->pessimistic)+doubleval($item->optimistic))/6;
        });
    }
}
