<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Requirement extends Model
{
    protected $fillable = [
        'name', 'impact', 'estimated_time', 'priority', 'details'
    ];

    public function users()
    {
        return $this->belongsToMany('App\User')->role('Analyst');
    }

    public function project()
    {
        return $this->belongsTo('App\Project');
    }

    public function items()
    {
        return $this->hasMany('App\Item');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::saving(function ($req) {
            $ttime = Item::where('requirement_id', $req->id)->sum('estimated');
            $req->estimated_time = $ttime;
        });
    }
}
